apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "azimuth-apps-operator.fullname" . }}
  labels: {{ include "azimuth-apps-operator.labels" . | nindent 4 }}
rules:
  # Manipulating CRDs (only allow patching of our own CRDs)
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - list
      - get
      - watch
      - create
