{{- if .Values.trustBundle }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "azimuth-apps-operator.fullname" . }}-trust-bundle
  labels: {{ include "azimuth-apps-operator.labels" . | nindent 4 }}
data:
  ca-certificates.crt: |
    {{- nindent 4 .Values.trustBundle }}
{{- end }}
