apiVersion: v1
kind: Secret
metadata:
  name: {{ include "azimuth-apps-operator.fullname" . }}
  labels: {{ include "azimuth-apps-operator.labels" . | nindent 4 }}
stringData:
  apps-operator.yaml: |
    !include "/etc/azimuth/defaults.yaml,/etc/azimuth/user-config.yaml"
  defaults.yaml: |
    {}
  user-config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
