{
 "title": "Azimuth / Apps",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Apps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total apps",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(topk(1, azimuth_apps_app_info) by (app_namespace, app_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "App phase",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(topk(1, azimuth_apps_app_phase{phase=~\".+\"}) by (app_namespace, app_name)) by (phase)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apps by namespace",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "sum(topk(1, azimuth_apps_app_info) by(app_namespace, app_name)) by(app_namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployed apps",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(topk(1, azimuth_apps_app_phase{phase=\"Deployed\"}) by(app_namespace, app_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed apps",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(topk(1, azimuth_apps_app_phase{phase=~\"Failed|Unknown\"}) by (app_namespace, app_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "App templates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "App templates",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(topk(1, azimuth_apps_template_info) by(template_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apps by template",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "sum(topk(1, azimuth_apps_app_info) by (app_namespace, app_name)) by (template_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outdated apps by template",
   "type": "timeseries",
   "description": "The number of apps running outdated versions of each app template",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 9 },
   "targets": [
    {
     "expr": "sum(topk(1, azimuth_apps_app_info unless (azimuth_apps_app_info * on(instance, template_name, template_version) group_left() label_replace(azimuth_apps_template_latest_version, \"template_version\", \"$1\", \"version\", \"(.+)\")))) by(template_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unsynced templates",
   "type": "stat",
   "description": "Number of templates that have not been synced for more than 24 hours",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((topk(1, azimuth_apps_template_last_sync) by(template_name) + 86400) < bool time())",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outdated apps",
   "type": "stat",
   "description": "The number of apps running an outdated version of a template",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(topk(1, azimuth_apps_app_info unless (azimuth_apps_app_info * on(instance, template_name, template_version) group_left() label_replace(azimuth_apps_template_latest_version, \"template_version\", \"$1\", \"version\", \"(.+)\"))) by(app_namespace, app_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "App template details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "App templates",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "topk(1, azimuth_apps_template_info * on(instance, template_name) group_left(latest_version) label_replace(azimuth_apps_template_latest_version, \"latest_version\", \"$1\", \"version\", \"(.+)\") * on(instance, template_name) group_left() azimuth_apps_template_last_sync * 1000) by(template_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(topk(1, azimuth_apps_template_version) by(template_name, version)) by(template_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(topk(1, azimuth_apps_app_info) by(app_namespace, app_name)) by(template_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "App details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Apps",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "label_join(topk(1, (azimuth_apps_app_info * on(instance, app_namespace, app_name) group_left(phase) azimuth_apps_app_phase * on(instance, template_name, template_version) group_left() label_replace(azimuth_apps_template_latest_version, \"template_version\", \"$1\", \"version\", \"(.+)\")) or (((azimuth_apps_app_info * on(instance, app_namespace, app_name) group_left(phase) azimuth_apps_app_phase) - 1) unless (azimuth_apps_app_info * on(instance, template_name, template_version) group_left() label_replace(azimuth_apps_template_latest_version, \"template_version\", \"$1\", \"version\", \"(.+)\")))) by (app_namespace, app_name), \"app\", \"/\", \"app_namespace\", \"app_name\")",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}